### ISSUE TITLE
Build too large for standard esp32-c3 devkitm-1

### ISSUE THREAD

**Issue by newcomertv** [nevi-me/esp32-c3-matter-minimal#1]
:~/git/third-parties/oxidized/esp32-c3-matter-minimal$ cargo espflash
New version of cargo-espflash is available: v2.0.0-rc.3

Serial port: /dev/ttyUSB0
Connecting...

warning: unused config key `build.channel` in `/home/_/git/third-parties/oxidized/esp32-c3-matter-minimal/.cargo/config.toml`
warning: Patch `chrono v0.4.19 (https://github.com/kedars/chrono#b0d13e54)` was not used in the crate graph.
Patch `ring v0.17.0-not-released-yet (https://github.com/esp-rs-compat/ring#ac8065f1)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling esp-idf-sys v0.32.1
   Compiling esp-idf-hal v0.40.1
   Compiling esp-idf-svc v0.45.0
   Compiling ws2812-esp32-rmt-driver v0.5.0
   Compiling esp32-c3-matter-minimal v0.1.0 (/home/_/git/third-parties/oxidized/esp32-c3-matter-minimal)
   Compiling matter-iot v0.1.0 (https://github.com/nevi-me/matter-rs?branch=esp32-c3-kedar-changes#d47951f8)
    Finished dev [optimized + debuginfo] target(s) in 30.25s
Chip type:         ESP32-C3 (revision 3)
Crystal frequency: 40MHz
Flash size:        4MB
Features:          WiFi
MAC address:       58:cf:79:e2:1b:18
App/part. size:    1905824/1048576 bytes, 181.75%
Error: 
  × Supplied elf image is too big and doesn't fit configured app partition

I tried building with --release  also too big for the standard C3, I'll try with an S3 when I get back home this evening

**Comment by nevi-me** [comment]
That's interesting, I'm able to flash it onto the same device. Looks like something's gone bad, i'll try it again and confirm if I also get the issue

**Comment by newcomertv** [comment]
I added a partitions.csv with one app partition needing at least 2M.
That fixes the issue:  
```csv
# ESP-IDF Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs, data, nvs, 0x9000, 0x6000,
otadata, data, ota, 0xf000, 0x2000,
test, app, factory, 0x20000, 0x240000,
```
